### ISSUE TITLE
合并到 DataX 主干

### ISSUE THREAD

**Issue by dingxiaobo** [StarRocks/DataX#15]
您好，我负责维护开源 DataX，我们想支持 StarRocks 读写功能，可以提一个PR给我们

https://github.com/alibaba/DataX

**Comment by userkdg** [comment]
+1

**Comment by userkdg** [comment]
> 您好，我负责维护开源 DataX，我们想支持 StarRocks 读写功能，可以提一个PR给我们
> 
> https://github.com/alibaba/DataX

这个能推动PR？
